import * as utils from './utils';
import UploadImg from './components/UploadImg';
import EnhanceTable from './components/EnhanceTable';
import WithSearch from './components/WithSearch';
import RenderDetail from './components/RenderDetail';
import HModal from './components/HModal';
import DaynamicForm from './components/DaynamicForm';
import formRender from './components/FormRender';
import FileUpload from './components/FileUpload';
export { utils, UploadImg, FileUpload, EnhanceTable, WithSearch, RenderDetail, HModal, formRender, DaynamicForm };